package it.polimi.ingsw.network.common.socket;

public enum SocketMessage {
    REGISTER_CLIENT_REQUEST,

    UNREGISTER_CLIENT_REQUEST,

    CLIENT_ALREADY_REGISTERED_ERROR,

    CLIENT_NOT_FOUND_ERROR,

    REGISTRATION_FAILED_ERROR,

    UNREGISTERING_FAILED_ERROR,

    REGISTRATION_SUCCESS,

    UNREGISTERING_SUCCESS,

    MESSAGE_INCOMING
}
